files:
  - source: /shell-volume-mixer@derhofbauer.at/locale/translations.pot
    translation: /shell-volume-mixer@derhofbauer.at/locale/%osx_locale%/LC_MESSAGES/gnome-shell-extensions-shell-volume-mixer.po
